import { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ReactQueryProvider } from './react-query-provider';
import { Toaster } from 'react-hot-toast';

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-Plus-Jakarta-Sans',
});

export const metadata: Metadata = {
  title: "CLOIT",
  description: "Generated by next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <ReactQueryProvider>
          <Toaster position="top-right"/>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
